Add documentation for the app
vtex-apps/product-gifts pull request #3
Opened 2020-02-25 20:51 UTC by victorhmp

#### What does this PR do?

Update the repo's README file to include the correct and updated documentation.

#### How to test it?

https://github.com/vtex-apps/product-gifts/blob/ee3d17f74f1854ec4fea2b7ab7c7826e1a27b41a/docs/README.md

2020-02-27 18:01 UTC, guerreirobeatriz requested changes
Everytime a documentation is born in this format and loaded w/ infos a fairy is born!!! 
Thanks for your contribution, Victor. 

I added some bullet points. Tell me how do you feel about them :)

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +1. Add the product-gifts app to your theme's dependencies in the `manifest.json`, for example:
1. Add the `product-gifts` app to your theme's dependencies in the `manifest.json` file, for example:

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +This is a block used for rendering the list of available gifts associated with a certain product in the Product Description Page (`store.product` template).
The Product Gifts app provides blocks responsible for displaying, in the Product Description block, all product gifts available.

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +| `maxVisibleItems` | `number` &#124; `"showAll"` | Maximum number of gifts that will be displayed at once | `"showAll"`   |
The type column is showing up  &#124 for me ):

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +Notice that this block will not work correctly outside of `store.product`.
Notice: the app must be in the product template (`store.product` ) in order to work properly once it is displayed along with the Product Description block.

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +Notice that this block will not work correctly outside of `store.product`.
I would add this sentence above the props table. What do you think?

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +2. Add the `product-gifts` block to your `store.product` template. For example:
Do we have any example not considering a PDP built on Flex Layout?  👀

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +This block has a default blocks implementation which is used when `product-gifts` is used in a theme and is not configured.
When declared in the `store.product` but not configured, the Product Gifts app has a default blocks implementation:

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +This app exposes multiple blocks that can be used _inside_ the `product-gifts` one using the `children` array.
As shown above, the app exports multiple blocks that can be configured in the `product-gifts` main block through a `children` array, such as:

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +### gift-text
### Gift Text

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +This is a block that is capable of reading information regarding the available gifts and use it to format the value of its `text` prop:
The `gift-text` is a block responsible for reading Catalog data regarding product gifts and using it to fill out the `text` prop value.

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +### gift-image
###  Gift Image

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +This block is responsible for rendering the image of the gift. It can receive an image label associated to the image that should be rendered, or it will just render the first available image for the
The `gift-image` block renders the product gift image. In order to function, it can use an pre-defined image label or the first available image from the product's SKU.

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +| `imageLabel` | `String`                 | The label of the image that should be rendered. | `undefined`   |
Image label that should be rendered.

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +| `maxWidth`   | `Number` &#124; `String` | Maximum width for the image.                    | `125`         |
Gift image maximum width

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +| `maxHeight`  | `Number` &#124; `String` | Maximum height for the image.                   | `125`         |
Gift image maximum height

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +| `minWidth`   | `Number` &#124; `String` | Minimum width for the image.                    | `125`         |
Gift image minimum width

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +| `minHeight`  | `Number` &#124; `String` | Minimum height for the image.                   | `125`         |
Gift image minimum height

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +### gift-description
### Gift Description

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +This block is responsible for rendering the gift's description.
As the name says, the `gift-description` renders a given gift's description.

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +
How it works? this description rendering? Should this process be more clarified here?

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +### gift-name
### Gift Name

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +| `linkToProductPage` | `Boolean` | Whether or not the gift-name should be a link to the gift's product page. | `false`       |
Whether or not the `gift-name` block should be a link to the gift's product page.

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +This block is responsible for rendering the SKU name for the gift.
The `gift-name` is responsible for rendering the SKU's gift name.

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +| `text`    | `String` | A translatable string that has variables that might be used to render any text regarding the gifts. | `"{exceedingItems, plural, =0{} one {+ # gift} other {+ # gifts}}"` |
For me, it is still confusing. I dont know if that due to the fact that im not a developer or if it can be more clearer to users. What do you think?

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +| `text`    | `String` | A translatable string that has variables that might be used to render any text regarding the gifts. | `"{exceedingItems, plural, =0{} one {+ # gift} other {+ # gifts}}"` |
Im referring to the prop description and how this block works (with the string and the variables)

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +### product-gift-list
### Product Gift List

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +This block is responsible for rendering the individual gifts as a list. It receives no props, but does receive blocks via `children`. Each block passed to it will be rendered as a gift-list item.
The `product-gift-list` is responsible for rendering the available gifts in a list format. 

Although it receives no props, it is able to receive blocks through a `children` array. Each block in the array will be rendered as a gift list item.

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +It also provides the necessary context to the its children that read information regarding each gift: `gift-name`, `gift-image` and `gift-description`.
Notice: the `product-gift-list` block provides the necessary context to its children regarding other gifts blocks, such as the Gift Name, Image and Description.

2020-02-27 18:01 UTC, guerreirobeatriz commented on docs/README.md
> +This block is responsible for rendering the individual gifts as a list. It receives no props, but does receive blocks via `children`. Each block passed to it will be rendered as a gift-list item.
I believe an example would be great here. I dont think I fully understood the product gift list functionality. What should I pass to the `children` array? All Gift blocks below, such as name, image, etc? If so, this should be clearer in their descriptions and they should be displayed as h4, not in the same level as their parent (product-gift-list).

2020-02-27 18:46 UTC, victorhmp commented on docs/README.md
> +Notice that this block will not work correctly outside of `store.product`.
Makes sense!

2020-03-03 13:53 UTC, guerreirobeatriz commented on docs/README.md
> +The Product Gifts app provides blocks responsible for displaying, in the Product Description block, all product gifts available.
The Product Gifts app provides blocks responsible for displaying, in the Product Description block, all gifts available for a given product.

ℹ️ _A product's gift is defined in a [Buy&Win promotion](https://help.vtex.com/tutorial/compre-ganhe-e-desconto-para-sku-especifico--frequentlyAskedQuestions_347#buy-win-gift-for-a-sku)._

2020-03-03 13:53 UTC, guerreirobeatriz commented on docs/README.md
> +2. Add the `product-gifts` block to your `store.product` template. For example:
2. Add the `product-gifts` block to your `store.product` template:

2020-03-03 13:53 UTC, guerreirobeatriz commented on docs/README.md
> +### Default implementation
### Advanced configuration

2020-03-03 13:53 UTC, guerreirobeatriz commented on docs/README.md
> +## Modus Operandi
This should be deleted.

2020-03-03 13:53 UTC, guerreirobeatriz commented on docs/README.md
> +:information_source: *A product's gift is configured in a [Buy&Win promotion](https://help.vtex.com/tutorial/buy-and-win--tutorials_322)
:information_source: *A product's gift is configured in a [Buy&Win promotion](https://help.vtex.com/tutorial/buy-and-win--tutorials_322)*.

2020-03-03 13:53 UTC, guerreirobeatriz commented on docs/README.md
> +:information_source: *A product's gift is configured in a [Buy&Win promotion](https://help.vtex.com/tutorial/buy-and-win--tutorials_322)
it was missing a * at the end of the sentence

2020-03-03 13:53 UTC, guerreirobeatriz commented on docs/README.md
> +![product-gifts-in-pdp](https://user-images.githubusercontent.com/27777263/75767692-f68d9800-5d21-11ea-87b9-aa4544f03698.png)
![product-gift](https://user-images.githubusercontent.com/52087100/75782082-20a08380-5d3d-11ea-9ae1-60873e03f1ac.png)

2020-03-03 14:24 UTC, merged